Fix Linux and Mac build!
Stupid bug in VAD where it's "more focussed" WEBRTC_POSIX flag was not
getting set and hence the compilation failed in POSIX systems.

```
Undefined symbols for architecture x86_64:
"_once", referenced from:
_WebRtcSpl_Init in libwebRTC.a(spl_init.c.o)
ld: symbol(s) not found for architecture x86_64
```
Replaced `WEBRTC_POSIX" with manual flag.